[package]
name = "edgelink-nodes-dummy"
version.workspace = true
edition = "2024"

[dependencies]
async-trait.workspace = true
tokio-util.workspace = true
log.workspace = true
config.workspace = true
inventory.workspace = true
edgelink-core = { path = "../../crates/core", default-features = false, features = [
    "core",
] }
edgelink-macro = { path = "../../crates/macro" }
